# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: cimg/python:3.11
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "setup.py" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python -m venv testenv
            source testenv/bin/activate
            pip install numpy
            pip install matplotlib

      - save_cache:
          paths:
            - ./testenv
          key: v1-dependencies-{{ checksum "setup.py" }}

      # run tests!
      - run:
          name: run tests
          command: |
            source testenv/bin/activate
            python -m cma.test

      - store_artifacts:
          path: test-reports
          destination: test-reports
          